### ISSUE TITLE
A bug of BKZ

### ISSUE THREAD

**Issue by yuyang-Tsinghua** [fplll/fpylll#104]
Hello,

I met a bug when I ran BKZ on a certain basis. BKZ worked well for beta = 11, 13, but for beta = 12, it reported a _math domain error_.  I am curious about the cause. Thank you.

The basis is attached as 'mat'
[bug.zip](https://github.com/fplll/fpylll/files/1454318/bug.zip)

The following is my script:

`from fpylll import IntegerMatrix, GSO
from fpylll.algorithms.bkz import BKZReduction as BKZ1
from fpylll import BKZ as BKZ

beta = 12
B = IntegerMatrix.from_file('mat')
gso_B = GSO.Mat(B, float_type="ld")
gso_B.update_gso()
param = BKZ.Param(block_size=beta)
BKZ1(gso_B)(params=param)`

**Comment by malb** [comment]
Dang, I pushed the bugfix to a feature branch instead of master. Thanks for making it so easy to debug!
