### ISSUE TITLE
Is it possible to construct IntegerMatrix with very large integers?

### ISSUE THREAD

**Issue by ethanleet** [fplll/fpylll#108]
When I tried to do so, it just tells me "OverflowError: Python int too large to convert to C long", and I didn't find a solution in the documentations.

**Comment by malb** [comment]
This should just work™, if it doesn't that's a bug. Which commands did you run? This works:

```python
In [1]: from fpylll import *
In [2]: A = IntegerMatrix(10, 10)
In [5]: A[0, 0] = 2**10000
```

**Comment by ethanleet** [comment]
Sorry for the late reply. I'm constructing an `IntegerMatrix` from a list of lists:
`B = IntegerMatrix.from_matrix(Bm)`
where Bm is the list that contains very large integers.
However, if I take modular 256 with all entries in B then it works just fine. Below is the full error message.
`Traceback (most recent call last):
  File "src/fpylll/fplll/integer_matrix.pyx", line 656, in fpylll.fplll.integer_matrix.IntegerMatrix.set_matrix
TypeError: list indices must be integers or slices, not tuple

During handling of the above exception, another exception occurred:

OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lcg.py", line 76, in <module>
    B = IntegerMatrix.from_matrix(Bm)
SystemError: <cyfunction IntegerMatrix.from_matrix at 0x10831a550> returned a result with an error set`

**Comment by malb** [comment]
Hi, can you post a minimal but complete failing example. I believe there's a bug here but I cannot reproduce it.

```python
A = IntegerMatrix.from_matrix([[2**20000]])
```

**Comment by ethanleet** [comment]
That's very odd. This line of code doesn't work for me either. Perhaps there're some dependency issues :(

**Comment by malb** [comment]
Mhh, are you running git master? Which OS/CPU?

**Comment by ethanleet** [comment]
Yes I used master. Running on macOS 10.13 with Intel Core i7-860.

**Comment by malb** [comment]
Oh, another one: Python 2 or 3?

**Comment by ethanleet** [comment]
Python 3.6.2

**Comment by malb** [comment]
Ah! I can now reproduce it:

```python
In [1]: from fpylll import *
In [2]: A = IntegerMatrix.from_matrix([[int(2)**20000]])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Projects/lattices/fpylll/src/fpylll/fplll/integer_matrix.pyx in fpylll.fplll.integer_matrix.IntegerMatrix.set_matrix()
    655                 for j in range(n):
--> 656                     self._set(i, j, A[i, j])
    657         except TypeError:

TypeError: list indices must be integers or slices, not tuple

During handling of the above exception, another exception occurred:

OverflowError                             Traceback (most recent call last)
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-2-1f6de7d6d160> in <module>()
----> 1 A = IntegerMatrix.from_matrix([[int(2)**20000]])

SystemError: <cyfunction IntegerMatrix.from_matrix at 0x7f03bc31a328> returned a result with an error set
```

**Comment by ethanleet** [comment]
Sounds great!
