### ISSUE TITLE
size_reduction segfault

### ISSUE THREAD

**Issue by malb** [fplll/fpylll#110]
The following was reported by Jean-Sebastien Coron:

```python
from fpylll import *
A = IntegerMatrix(4, 4)
A.randomize("ntrulike", bits=50, q=127)
M = GSO.Mat(A)
M.update_gso()
L = LLL.Reduction(M)
L.size_reduction()
```

**Boom** (Segfault)

**Comment by shi-bai** [comment]
Martin, this is a nice fix. I pushed the button.

Just log the details here: the internal data babai_mu and babai_expo is used in member function size_reduction but they were only initialized after calling lll() first. Sometimes we want to just use size_reduction() without calling lll() and therefore triggers the seg error.
