### ISSUE TITLE
RTD docbuild fails because fplll::MatrixRow<...> has no member named ‘dot_product’

### ISSUE THREAD

**Issue by jdemeyer** [fplll/fpylll#117]
On readthedocs, building `fpylll` fails with
```
build/src/fpylll/fplll/integer_matrix.cpp:3236:58: error: ‘class fplll::MatrixRow<fplll::Z_NR<__mpz_struct [1]> >’ has no member named ‘dot_product’
```

**Comment by jdemeyer** [comment]
> Dang, can we ask RTD to build the last tag instead of master?

I guess so, I'll need to check.

> Otherwise, I think the problem will keep re-appearing. Thanks for reporting, I should really have an eye on that myself!

One solution would be to compile `fplll` from git master instead of using `fplll` from conda.

**Comment by malb** [comment]
I think this is fixed now.
