### ISSUE TITLE
CVP/enumeration function in fpylll fails to output a "shortest" vector

### ISSUE THREAD

**Issue by taechan-kim** [fplll/fpylll#124]
I recently found a possible bug in CVP function of fpylll.
I sent an email on this to Martin, and we decided to discuss this issue here.

I have run the following on SageMath ver 8.0. on my mac.

###

A = IntegerMatrix.from_matrix( [ [629, 303, 597, 980],
 [462, 533, 231, 443],
 [912, 451, 926, 105],
 [162, 742, 611, 734] ] )

t = (123, 456, 345, 578)

CVP.closest_vector(A, t)

###

Then, it outputs (162, 742, 611, 734) as a solution, where the square of the distance norm is 178409.

On the other hand, I tried to run my own implementation based on the paper by Liu and Nguyen,
then I've got a shorter solution:

[462 533 231 443]

whose distance norm is 152071, which is smaller than the previous.

**Comment by malb** [comment]
`closest_vector` assumes that the input basis is LLL reduced. I just pushed a documentation update to that effect.
