### ISSUE TITLE
setup.py build_ext se fails

### ISSUE THREAD

**Issue by MiBu84** [fplll/fpylll#129]
Executed successfully all steps up to "6. Build the Python extension:"

My config: 
- CentOS 7 (uname -r --> 4.19.7-1.el7.elrepo.x86_64), 
-gcc -v --> gcc-Version 4.8.5 20150623 (Red Hat 4.8.5-36)  (also tried 5.4, 8.2)
- python --version  --> Python 3.6.5
- pip 18.1 from /home/mburger/env/lib/python3.6/site-packages/pip (python 3.6)
- echo $PKG_CONFIG_PATH --> /home/mburger/env/lib/pkgconfig
- ls /home/mburger/env/lib/pkgconfig --> fplll.pc
- echo $CPATH --> /home/mburger/module/packages/gmp/6.1.2/include
- ls /home/mburger/module/packages/gmp/6.1.2/include --> gmp.h

However when now trying "python3.6 setup.py build_ext", I receive:
unning build_ext
Package fplll was not found in the pkg-config search path.
Perhaps you should add the directory containing `fplll.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fplll' found
building 'fpylll.gmp.pylong' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c build/src/fpylll/gmp/pylong.c -o build/temp.linux-x86_64-3.6/build/src/fpylll/gmp/pylong.o
build/src/fpylll/gmp/pylong.c:637:17: schwerwiegender Fehler: gmp.h: Datei oder Verzeichnis nicht gefunden
 #include "gmp.h"
                 ^
Kompilierung beendet.
error: command 'gcc' failed with exit status 1

**Comment by malb** [comment]
You are missing GMP headers on your system. The relevant package will be called `gmp-dev` or `libgmp-devel` or so.

**Comment by MiBu84** [comment]
But I installed gmp (6.1.2) already and the Libs are in LD_LIBRARY_PATH/LIBRARY_PATH and the headers in CPATH. It is e.g. detected when compiling fplll directly or other costum projects requiring gmp.h during compilation and the libarary during linking.

**Comment by malb** [comment]
Closing this, it doesn't seem like a bug in fpylll. Feel free to reopen if you're convinced it is.
