### ISSUE TITLE
[need help] BKZ reduction error：  infinite loop in babai

### ISSUE THREAD

**Issue by ZiqiangMa** [fplll/fpylll#130]
Hello，
       My name is Ziqiang Ma. Recently I am using fpylll library to do the lattice attack in order to recover the ECDSA nounce. When I compute the SVP using BKZ algorithm in the fpylll library,  I have some problems. I searched on the internet and found no answers. So I hope that you could help me.
      
Here is my running code: 
```
    from fpylll import BKZ as fplll_bkz
    block_size=10
    params = fplll_bkz.Param(block_size=block_size, flags=fplll_bkz.VERBOSE|fplll_bkz.GH_BND)
    A2 = fplll_bkz.reduction(copy(CVPlattice), params)
```

CVPlattice is the input matrix.
When I run the code, It occurs the following errors:

 _terminate called after throwing an instance of 'std::runtime_error'
  what():  infinite loop in babai
Traceback (most recent call last):

  File "<ipython-input-1-9d69059d13d1>", line 1, in <module>
    runfile('/home/mzq/.config/spyder-py3/attack_ecdsa.py', wdir='/home/mzq/.config/spyder-py3')

  File "/home/mzq/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/home/mzq/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/mzq/.config/spyder-py3/attack_ecdsa.py", line 226, in <module>
    A2 = fplll_bkz.reduction(copy(CVPlattice), params)

  File "src/fpylll/fplll/bkz.pyx", line 1131, in fpylll.fplll.bkz.bkz_reduction

RuntimeError: Aborted_

I also use random matrix to compute the BKZ:

```
    def make_integer_matrix(n,bit=200):
        A = IntegerMatrix.random(n, "uniform", bits=bit)
        return A
```

When the matrix type is "uniform",  BKZ is executed successfully. 
However, if the matrix type is "ntrulike",  the code breaks down and meets the same errors.

I wonder to know that , if you have the problems when you did the experiments. And how you solved the problems?

I am very appreciate if you could help me.

**Comment by malb** [comment]
You'll likely need to run with a higher floating point precision, see the `float_type` parameter. You can try e.g. "ld", "dd" or "mpfr" (but in this case call FPLLL.set_precision() first)

**Comment by identitymapping** [comment]
@malb Could you please give me an example?I also encounter this problme runtime_error when using bkz algorithm.
