### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by lqliumeng** [fplll/fpylll#142]
Excuse me, fpylll takes about three days to process 450*450 dimension data at β=80, but the same data is still not finished after running for three weeks at β=90. What is the reason for this? Or is there any need  to change some relevant parameters? By the way, for the data that need the change of the precision paramater for processing, could there be any precesion number that you can recommond to us?

**Comment by lducas** [comment]
The running time of BKZ with enumeration (as implemented in fplll) is super-exponential in β, so it should not come as a surprise that β=90 is much slower than β=80. 

This can be mitigated using multi-threaded implementation of enumeration or of other algorithms than enumeration inside BKZ:
- https://link.springer.com/chapter/10.1007/978-3-030-22750-0_48
- https://github.com/cr-marcstevens/fplll-extenum/
- https://eprint.iacr.org/2019/089

Best of luck.
