### ISSUE TITLE
Default strategy inside SageMath 8.8 Binaries

### ISSUE THREAD

**Issue by lducas** [fplll/fpylll#147]
I'm having trouble using the default strategies inside SageMath 8.8 (linux binaries). Not sure if it should be reported here or to sage
`
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 8.8, Release Date: 2019-06-26                     │
│ Using Python 2.7.15. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘

sage: from fpylll import *
sage: BKZ.DEFAULT_STRATEGY
....: 
'/export/scratch1/ducas/SageMath/local/share/fplll/strategieparse error - unpreprocessing_blpruning_parameteError: gptr == nullpos/default.json'
sage: BKZ.DEFAULT_STRATEGY_PATH
'/export/scratch1/ducas/SageMath/local/share/fplll/strategieparse error - unpreprocessing_blpruning_parameteError: gptr == nullpos'
sage: 
`

**Comment by malb** [comment]
This looks like a Sage bug to me. Building Sage from source, I don't have this problem so seems to be an issue with the buildbot?

**Comment by malb** [comment]
This is now https://trac.sagemath.org/ticket/28664
