### ISSUE TITLE
Is this equation right？

### ISSUE THREAD

**Issue by SunZeDong** [fplll/fpylll#148]
https://github.com/fplll/fpylll/blob/ec1c071606a776cef6e2519a7c0fae6343de9053/src/fpylll/util.pyx#L265

According to Gaussian Heuristic, gh(L) = ( vol(L) / vol( ball_1(n) ) )^(1/n), 
so in the equation "log_gh =  1./n * (log_vol - 2 * ball_log_vol(n))" how comes 2 ?

**Comment by malb** [comment]
We store norms squared in FP(y)LLL, so log_vol is really `2*log(Vol)`.
