### ISSUE TITLE
Python2 / Python3

### ISSUE THREAD

**Issue by cbouilla** [fplll/fpylll#164]
Hi everyone,

The `bootstrap.sh` script provided in this repo works like a charm, but on my machine it creates a python2 extension. I had to patch it to obtain a python3 module (not that python2 is deprecated).

I just add to update line 5 of the script with
`virtualenv --python=python3 fpylll-env`

**Comment by malb** [comment]
This is annoying. I think `python3` being the name of the executable for Python 3 should only be temporary. In particular, I'm not sure hardcoding `python3` would work across distributions?

**Comment by cbouilla** [comment]
I have Debian 10 ("buster"). For me `virtualenv`says : 
```
$ virtualenv
Running virtualenv with interpreter /usr/bin/python2
You must provide a DEST_DIR
Usage: virtualenv.py [OPTIONS] DEST_DIR

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -v, --verbose         Increase verbosity.
  -q, --quiet           Decrease verbosity.
  -p PYTHON_EXE, --python=PYTHON_EXE
                        The Python interpreter to use, e.g.,
                        --python=python2.5 will use the python2.5 interpreter
                        to create the new environment.  The default is the
                        python2 interpreter on your path (e.g.
                        /usr/bin/python2)
```

So apparently it defaults to python2.
