### ISSUE TITLE
Error/Warning when blocksize > basis dimension

### ISSUE THREAD

**Issue by fvirdia** [fplll/fpylll#167]
BKZ calls seem to quietly return (with no work done) when called on basis that have dimension < block size. When one could argue this should lead to an HKZ reduced basis, it would probably be fine to raise a `ValueError` instead. If one really wants an HKZ reduced basis, it should be fine to set the block size equal to the basis dimension.

**Comment by fvirdia** [comment]
On further investigation, it seems the behaviour of fpylll depends on the BKZ strategy used. In particular, from the behaviour below it seems that `BKZ.DEFAULT_STRATEGY` is not the default value for the `strategy` keyword in `BKZ.Param`

```python
from fpylll import *
from fpylll.algorithms.bkz2 import BKZReduction as BKZ2
FPLLL.set_random_seed(1337)
A = IntegerMatrix.random(50, "qary", k=25, bits=30)
bkz = BKZ2(A)

# no work done:
_ = bkz(BKZ.Param(60, strategies=BKZ.DEFAULT_STRATEGY, max_loops=4, flags=BKZ.AUTO_ABORT|BKZ.MAX_LOOPS|BKZ.GH_BND|BKZ.VERBOSE)) 

# work is done (no warning on block size > dimension):
_ = bkz(BKZ.Param(60))

# work is done (no warning on block size > dimension):
_ = bkz(BKZ.Param(60, max_loops=4, flags=BKZ.AUTO_ABORT|BKZ.MAX_LOOPS|BKZ.GH_BND|BKZ.VERBOSE))
```

**Comment by malb** [comment]
That behaviour seems correct to me:
- `BKZ.Param` indeed does not pick a strategies, `BKZ.EasyParam` is meant for that.
- As far as I can tell, the first line does work, it's just fast.  

```python
sage: A = LLL.reduction(IntegerMatrix.random(50, "qary", k=25, bits=30))
sage: round(A[0].norm()**2)
486095115.0
sage: _ = bkz(param)
{"i":        0,  "cputime": 0.191292,  "walltime": 0.191232,  "preproc": 0.163584,  "svp": 0.020310,  "#enum":   2^13.4,  "lll": 0.035716,  "pruner": 0.002694,  "r_0":   2^29.8,  "/": -0.05398}
sage: round(A[0].norm()**2)
486095115.0
sage: _ = bkz(BKZ.Param(60))
sage: round(A[0].norm()**2)
486095115.0
```

**Comment by malb** [comment]
Closing?

**Comment by fvirdia** [comment]
sounds good
