### ISSUE TITLE
libfp111.so.6 missing

### ISSUE THREAD

**Issue by johughes99** [fplll/fpylll#169]
On trying to run some python code I get the following error:

  from fpylll import LLL, BKZ, CVP, IntegerMatrix, GSO, Enumeration, Pruning, EnumerationError
  File "/home/johughes/.local/lib/python3.6/site-packages/fpylll/__init__.py", line 3, in <module>
    from .fplll.integer_matrix import IntegerMatrix
ImportError: libfplll.so.6: cannot open shared object file: No such file or directory

I have successfully installed fplll in a previous step - getting the latest source from GitHuB. So not sure what it's look for.

**Comment by malb** [comment]
Did you `export LD_LIBRARY_PATH="$VIRTUAL_ENV/lib"` ?

**Comment by johughes99** [comment]
Many thanks  - that sorted it out.

**Comment by bo-hub** [comment]
Hi, I faced the same issue  

`ImportError: libfplll.so.8: cannot open shared object file: No such file or directory` 

How to use this command `export LD_LIBRARY_PATH="$VIRTUAL_ENV/lib"` ?
@malb

**Comment by bo-hub** [comment]
Should I change the `$VIRTUAL_ENV` to some specific path?

**Comment by bo-hub** [comment]
I find my libfplll.so file in /usr/local/lib.
I add `export LD_LIBRARY_PATH=/usr/local/lib` in .bashrc file. Reload the terminal. Then this solved.
