### ISSUE TITLE
fatal error: fplll/nr/nr.h: No such file or directory  #include "fplll/nr/nr.h"

### ISSUE THREAD

**Issue by chrisyang2003** [fplll/fpylll#173]
I don't know why this program goes wrong, i can't figure out it
![image](https://user-images.githubusercontent.com/63803385/84513483-13137600-acfc-11ea-86d1-9da242ef8f21.png)

**Comment by 908875137** [comment]
I have the same problem.

**Comment by malb** [comment]
There isn't really enough to go on in this bug report.

**Comment by malb** [comment]
Nothing happening, closing.
