### ISSUE TITLE
RuntimeError for CVP.closest_vector

### ISSUE THREAD

**Issue by heweifred** [fplll/fpylll#180]
When implementing `CVP.closest_vector(A, t)` I encounter following error

`RuntimeError: Aborted`

My A has dimension (259, 285). Is the program aborted because the dimension is too large? Is there a way to still let the program run? (My A is very sparse; for a similar case I had A of dimension (145, 171) and CVP.closest_vector finds solution within a second)

**Comment by karthickgopalswamy** [comment]
I had similar issue. Dug a bit into the underlying c++ code. I see that the maximum possible enumeration size is set at 256. In your case this raises an error in the underlying c++ function. Since the error is not passed on to the python bindings you get a general runtime error.
