### ISSUE TITLE
svp_postprocessing docstring

### ISSUE THREAD

**Issue by fvirdia** [fplll/fpylll#183]
The current docstring for postprocessing claims that LLL is called. However, it seems the only call to LLL in the method has been commented. Is this just an outdated docstring?

https://github.com/fplll/fpylll/blob/2347a08b9ccbdf34376f4cff72ccdac1d611858a/src/fpylll/algorithms/bkz.py#L215

**Comment by malb** [comment]
I agree.

**Comment by fvirdia** [comment]
I believe this is now resolved.
