### ISSUE TITLE
Add install_requires to setup.py/setup.cfg, or add pyproject.toml

### ISSUE THREAD

**Issue by mkoeppe** [fplll/fpylll#185]
On a system with fplll installed, `pip install fpylll` fails because the distribution does not declare its Python build dependencies.

**Comment by malb** [comment]
We're using `distutils` which doesn't know `install_requires` and I dread adding more of these meta files to the toplevel directory of the project. I'm inclined to close this as wontfix. How big of an issue is it?

**Comment by mkoeppe** [comment]
> How big of an issue is it?
It's critical because it makes it impossible for another Python project to declare a dependency on fpylll.

**Comment by malb** [comment]
Okay, the PR referenced above should do what is needed.
