### ISSUE TITLE
fpylll build wheel failing using pip

### ISSUE THREAD

**Issue by SinTan1729** [fplll/fpylll#202]
I'm unable to update `fpylll` using `pip`. The build cycle keeps failing.

[Here's](https://pastebin.com/x2aMDqy5) the output I'm getting.

**Comment by malb** [comment]
Did you install Cython and cysignals first?

**Comment by SinTan1729** [comment]
Yes, both of those packages are installed.

```
pacman -Qs cython
local/cython 0.29.21-1
    C-Extensions for Python
local/python-cypari2 2.1.2-1
    Cython bindings for PARI
local/python-cysignals 1.10.2-6
    Interrupt and signal handling for Cython
local/python-pyzmq 19.0.1-2
    Python3 bindings for zeromq, written in Cython
local/python2-pyzmq 19.0.1-2
    Python2 bindings for zeromq, written in Cython
```

**Comment by malb** [comment]
Mhh, okay, your error report doesn't seem to have enough details to debug this. Is there a "verbose" option?

**Comment by SinTan1729** [comment]
Somehow got fixed after a rather huge Manjaro update. I'm not sure what exactly fixed it, but hey.
