### ISSUE TITLE
error building - using gcc instead of g++

### ISSUE THREAD

**Issue by themaddoctor** [fplll/fpylll#207]
This is my experience building fpylll:

python3 setup.py install --root="$PWD/../build"
running install
running build
running build_py
running build_ext
building 'fpylll.fplll.enumeration' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/fpylll/fplll -I/usr/lib/python3.7/site-packages/cysignals -I/usr/include -I/usr/lib/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c build/src/fpylll/fplll/enumeration.cpp -o build/temp.linux-x86_64-3.7/build/src/fpylll/fplll/enumeration.o -std=c++11
build/src/fpylll/fplll/enumeration.cpp: In function 'PyObject* __pyx_pf_6fpylll_5fplll_11enumeration_11Enumeration_6get_nodes(__pyx_obj_6fpylll_5fplll_11enumeration_Enumeration*, PyObject*)':
build/src/fpylll/fplll/enumeration.cpp:5948:99: error: no matching function for call to 'fplll::Enumeration<fplll::Z_NR<__mpz_struct [1]>, fplll::FP_NR<double> >::get_nodes(int&)'
 yInt_From_unsigned_long(__pyx_v_self->_core.mpz_d->get_nodes(__pyx_v__level)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 576, __pyx_L1_error)
                                                                            ^
In file included from /usr/include/fplll/bkz.h:22:0,
                 from /usr/include/fplll/fplll.h:25,
                 from build/src/fpylll/fplll/enumeration_callback_helper.h:6,
                 from build/src/fpylll/fplll/enumeration.cpp:671:
/usr/include/fplll/enum/enumerate.h:103:19: note: candidate: uint64_t fplll::Enumeration<ZT, FT>::get_nodes() const [with ZT = fplll::Z_NR<__mpz_struct [1]>; FT = fplll::FP_NR<double>; uint64_t = long unsigned int]
   inline uint64_t get_nodes() const { return _nodes; }
                   ^~~~~~~~~
/usr/include/fplll/enum/enumerate.h:103:19: note:   candidate expects 0 arguments, 1 provided
build/src/fpylll/fplll/enumeration.cpp:5981:100: error: no matching function for call to 'fplll::Enumeration<fplll::Z_NR<__mpz_struct [1]>, fplll::FP_NR<long double> >::get_nodes(int&)'
 Int_From_unsigned_long(__pyx_v_self->_core.mpz_ld->get_nodes(__pyx_v__level)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 579, __pyx_L1_error)
                                                                            ^
In file included from /usr/include/fplll/bkz.h:22:0,
                 from /usr/include/fplll/fplll.h:25,
                 from build/src/fpylll/fplll/enumeration_callback_helper.h:6,
                 from build/src/fpylll/fplll/enumeration.cpp:671:
/usr/include/fplll/enum/enumerate.h:103:19: note: candidate: uint64_t fplll::Enumeration<ZT, FT>::get_nodes() const [with ZT = fplll::Z_NR<__mpz_struct [1]>; FT = fplll::FP_NR<long double>; uint64_t = long unsigned int]
   inline uint64_t get_nodes() const { return _nodes; }
                   ^~~~~~~~~
/usr/include/fplll/enum/enumerate.h:103:19: note:   candidate expects 0 arguments, 1 provided
build/src/fpylll/fplll/enumeration.cpp:6014:101: error: no matching function for call to 'fplll::Enumeration<fplll::Z_NR<__mpz_struct [1]>, fplll::FP_NR<dpe_struct [1]> >::get_nodes(int&)'
 nt_From_unsigned_long(__pyx_v_self->_core.mpz_dpe->get_nodes(__pyx_v__level)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 581, __pyx_L1_error)
                                                                            ^
In file included from /usr/include/fplll/bkz.h:22:0,
                 from /usr/include/fplll/fplll.h:25,
                 from build/src/fpylll/fplll/enumeration_callback_helper.h:6,
                 from build/src/fpylll/fplll/enumeration.cpp:671:
/usr/include/fplll/enum/enumerate.h:103:19: note: candidate: uint64_t fplll::Enumeration<ZT, FT>::get_nodes() const [with ZT = fplll::Z_NR<__mpz_struct [1]>; FT = fplll::FP_NR<dpe_struct [1]>; uint64_t = long unsigned int]
   inline uint64_t get_nodes() const { return _nodes; }
                   ^~~~~~~~~
/usr/include/fplll/enum/enumerate.h:103:19: note:   candidate expects 0 arguments, 1 provided
build/src/fpylll/fplll/enumeration.cpp:6047:102: error: no matching function for call to 'fplll::Enumeration<fplll::Z_NR<__mpz_struct [1]>, fplll::FP_NR<__mpfr_struct [1]> >::get_nodes(int&)'
 t_From_unsigned_long(__pyx_v_self->_core.mpz_mpfr->get_nodes(__pyx_v__level)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 588, __pyx_L1_error)
                                                                            ^
In file included from /usr/include/fplll/bkz.h:22:0,
                 from /usr/include/fplll/fplll.h:25,
                 from build/src/fpylll/fplll/enumeration_callback_helper.h:6,
                 from build/src/fpylll/fplll/enumeration.cpp:671:
/usr/include/fplll/enum/enumerate.h:103:19: note: candidate: uint64_t fplll::Enumeration<ZT, FT>::get_nodes() const [with ZT = fplll::Z_NR<__mpz_struct [1]>; FT = fplll::FP_NR<__mpfr_struct [1]>; uint64_t = long unsigned int]
   inline uint64_t get_nodes() const { return _nodes; }
                   ^~~~~~~~~
/usr/include/fplll/enum/enumerate.h:103:19: note:   candidate expects 0 arguments, 1 provided
build/src/fpylll/fplll/enumeration.cpp:6080:100: error: no matching function for call to 'fplll::Enumeration<fplll::Z_NR<long int>, fplll::FP_NR<double> >::get_nodes(int&)'
 Int_From_unsigned_long(__pyx_v_self->_core.long_d->get_nodes(__pyx_v__level)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 591, __pyx_L1_error)
                                                                            ^
In file included from /usr/include/fplll/bkz.h:22:0,
                 from /usr/include/fplll/fplll.h:25,
                 from build/src/fpylll/fplll/enumeration_callback_helper.h:6,
                 from build/src/fpylll/fplll/enumeration.cpp:671:
/usr/include/fplll/enum/enumerate.h:103:19: note: candidate: uint64_t fplll::Enumeration<ZT, FT>::get_nodes() const [with ZT = fplll::Z_NR<long int>; FT = fplll::FP_NR<double>; uint64_t = long unsigned int]
   inline uint64_t get_nodes() const { return _nodes; }
                   ^~~~~~~~~
/usr/include/fplll/enum/enumerate.h:103:19: note:   candidate expects 0 arguments, 1 provided
build/src/fpylll/fplll/enumeration.cpp:6113:101: error: no matching function for call to 'fplll::Enumeration<fplll::Z_NR<long int>, fplll::FP_NR<long double> >::get_nodes(int&)'
 nt_From_unsigned_long(__pyx_v_self->_core.long_ld->get_nodes(__pyx_v__level)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 594, __pyx_L1_error)
                                                                            ^
In file included from /usr/include/fplll/bkz.h:22:0,
                 from /usr/include/fplll/fplll.h:25,
                 from build/src/fpylll/fplll/enumeration_callback_helper.h:6,
                 from build/src/fpylll/fplll/enumeration.cpp:671:
/usr/include/fplll/enum/enumerate.h:103:19: note: candidate: uint64_t fplll::Enumeration<ZT, FT>::get_nodes() const [with ZT = fplll::Z_NR<long int>; FT = fplll::FP_NR<long double>; uint64_t = long unsigned int]
   inline uint64_t get_nodes() const { return _nodes; }
                   ^~~~~~~~~
/usr/include/fplll/enum/enumerate.h:103:19: note:   candidate expects 0 arguments, 1 provided
build/src/fpylll/fplll/enumeration.cpp:6146:102: error: no matching function for call to 'fplll::Enumeration<fplll::Z_NR<long int>, fplll::FP_NR<dpe_struct [1]> >::get_nodes(int&)'
 t_From_unsigned_long(__pyx_v_self->_core.long_dpe->get_nodes(__pyx_v__level)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 596, __pyx_L1_error)
                                                                            ^
In file included from /usr/include/fplll/bkz.h:22:0,
                 from /usr/include/fplll/fplll.h:25,
                 from build/src/fpylll/fplll/enumeration_callback_helper.h:6,
                 from build/src/fpylll/fplll/enumeration.cpp:671:
/usr/include/fplll/enum/enumerate.h:103:19: note: candidate: uint64_t fplll::Enumeration<ZT, FT>::get_nodes() const [with ZT = fplll::Z_NR<long int>; FT = fplll::FP_NR<dpe_struct [1]>; uint64_t = long unsigned int]
   inline uint64_t get_nodes() const { return _nodes; }
                   ^~~~~~~~~
/usr/include/fplll/enum/enumerate.h:103:19: note:   candidate expects 0 arguments, 1 provided
build/src/fpylll/fplll/enumeration.cpp:6176:103: error: no matching function for call to 'fplll::Enumeration<fplll::Z_NR<long int>, fplll::FP_NR<__mpfr_struct [1]> >::get_nodes(int&)'
 _From_unsigned_long(__pyx_v_self->_core.long_mpfr->get_nodes(__pyx_v__level)); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 603, __pyx_L1_error)
                                                                            ^
In file included from /usr/include/fplll/bkz.h:22:0,
                 from /usr/include/fplll/fplll.h:25,
                 from build/src/fpylll/fplll/enumeration_callback_helper.h:6,
                 from build/src/fpylll/fplll/enumeration.cpp:671:
/usr/include/fplll/enum/enumerate.h:103:19: note: candidate: uint64_t fplll::Enumeration<ZT, FT>::get_nodes() const [with ZT = fplll::Z_NR<long int>; FT = fplll::FP_NR<__mpfr_struct [1]>; uint64_t = long unsigned int]
   inline uint64_t get_nodes() const { return _nodes; }
                   ^~~~~~~~~
/usr/include/fplll/enum/enumerate.h:103:19: note:   candidate expects 0 arguments, 1 provided
error: command 'gcc' failed with exit status 1

**Comment by malb** [comment]
Looks like your FPLLL and FPyLLL versions don't match up.

**Comment by themaddoctor** [comment]
Is there a fplll 0.5.5? It's not on github

**Comment by malb** [comment]
FPLLL 5.4.0 should do.

**Comment by themaddoctor** [comment]
Thanks!

**Comment by themaddoctor** [comment]
quick question: what happened to latsieve?

**Comment by malb** [comment]
> quick question: what happened to latsieve?

We removed it, see https://github.com/fplll/fplll/pull/457

**Comment by malb** [comment]
This seems to be resolved, closing for now. Feel free to reopen if the issue persists.
