### ISSUE TITLE
Potentially outdated docstring

### ISSUE THREAD

**Issue by fvirdia** [fplll/fpylll#213]
When checking the documentation for `GSO.Mat` for the use of `float_type`, the [docstring](https://github.com/fplll/fpylll/blob/cc99217d4bc793649a6d9d4950a899fea408092d/src/fpylll/fplll/gso.pyx#L123) suggests that allowed floating point types are elements of ``fpylll.fpylll.float_types``. I believe the latter does not exist, maybe ``fpylll.config.float_types`` was intended? [These](https://github.com/fplll/fpylll/blob/cc99217d4bc793649a6d9d4950a899fea408092d/src/fpylll/fplll/lll.pyx#L561) two [docstrings](https://github.com/fplll/fpylll/blob/cc99217d4bc793649a6d9d4950a899fea408092d/src/fpylll/fplll/bkz.pyx#L1115) seem to erroneously mention ``fpylll.float_types`` instead.

**Comment by malb** [comment]
I agree, it should be `fpylll.config.float_types`
