### ISSUE TITLE
Path issue in Sage

### ISSUE THREAD

**Issue by joerowell** [fplll/fpylll#218]
The [filtered s-unit](https://s-unit.attacks.cr.yp.to/filtered.html) codebase has this wrapper in it:

``` sage
import fpylll

# not just for speed; also deals with "cannot open strategies file" fpylll bug
try:
  fn = fpylll.BKZ.DEFAULT_STRATEGY
  if not fn.startswith('/'):
    fn = fpylll.BKZ.DEFAULT_STRATEGY_PATH+'/'+fn
except TypeError:
  fn = fpylll.BKZ.DEFAULT_STRATEGY
  if not fn.startswith(b'/'):
    fn = fpylll.BKZ.DEFAULT_STRATEGY_PATH+b'/'+fn
precomputed_bkz_strategies = fpylll.load_strategies_json(fn)

def bkz(M,beta):
  return M.BKZ(block_size=beta,strategies=precomputed_bkz_strategies)
```

It turns out that the value of ```BKZ.DEFAULT_STRATEGY``` has different values inside Sage vs Ipython:

Sage:
```python
import fpylll
print(fpylll.BKZ.DEFAULT_STRATEGY)
>>> b'default.json'
```

Ipython:

```python
import fpylll
print(fpylll.BKZ.DEFAULT_STRATEGY)
>>> b' /home/j/.conda/envs/fp/share/fplll/strategies/default.json
```

I don't know if this is something that is easily resolvable, but I figured it's better to have a record of it. I'd wager that it's to do with Sage doing some clever path magic when it runs.

**Comment by malb** [comment]
I don't think that's a Sage vs iPython thing. My local Sage has the right path. I think it's a precompiled Sage vs locally compiled iPython/FPyLLL thing?

**Comment by malb** [comment]
We could add a hack and fall back to 
```python
os.path.join(os.environ["SAGE_LOCAL"], "fplll", "strategies", "default.json")
```
when we cannot load the strategies on the first try?
