### ISSUE TITLE
readthedocs

### ISSUE THREAD

**Issue by malb** [fplll/fpylll#22]
Putting the documentation up on https://readthedocs.org would be useful … once we figure out how to build Cython modules heavily dependent on C libraries to build there.

**Comment by jdemeyer** [comment]
I recently worked on ReadTheDocs for `cysignals` and managed to make it work, even with autodoc. So I might help here.

**Comment by jdemeyer** [comment]
Just started working on this: https://readthedocs.org/projects/fpylll/builds/

**Comment by malb** [comment]
Thanks, let me know how I can help.

**Comment by jdemeyer** [comment]
I'm developing this at https://github.com/jdemeyer/fpylll (use the `master` branch).

I'm stuck at this C++ issue:
```
ImportError: /home/docs/checkouts/readthedocs.org/user_builds/fpylll/conda/latest/lib/python2.7/site-packages/fpylll/fplll/bkz_param.so: undefined symbol: _ZN5fplll18strategy_full_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

It seems that ReadTheDocs is doing name mangling differently (on my system, the symbol `_ZN5fplll18strategy_full_pathERKSs` exists but not `_ZN5fplll18strategy_full_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`).
