### ISSUE TITLE
Enumeration to find short vectors

### ISSUE THREAD

**Issue by Alexander-commits** [fplll/fpylll#232]
Is it possible to use fpylll methods such as the enumeration to find many short lattice vectors? Or is it better to use sieving algorithms?

**Comment by malb** [comment]
You *can* but if you're investing exponential memory to store all these vectors, you might as well use the faster sieving algorithm to begin with? We effectively do this, inspecting many short vectors in a ball, in e.g. https://github.com/malb/bdd-predicate/
