### ISSUE TITLE
The chiral reservation of the lattice basis before and after lattice reduction.

### ISSUE THREAD

**Issue by hongyi-zhao** [fplll/fpylll#237]
Suppose `A` is the original lattice, and `B` is the result obtained by lattice reduction. If I want to retain the chirality of the bases before and after the lattice reduction, aka, `Det[A] == Det[B]`. I'm not sure whether this is possible.

See [here](https://community.wolfram.com/groups/-/m/t/2686113) for the related discussion.

Regards,
Zhao

**Comment by malb** [comment]
Lattice reduction is multiplication by an unimodular transformation matrix and thus leaves the determinant unchanged.

**Comment by hongyi-zhao** [comment]
By convention, an unimodular matrix M is a [square](https://en.wikipedia.org/wiki/Square_matrix) [integer matrix](https://en.wikipedia.org/wiki/Integer_matrix) having [determinant](https://en.wikipedia.org/wiki/Determinant) +1 or -1, as described below:

![image](https://user-images.githubusercontent.com/11155854/213454732-c627ad4c-4a54-46c7-8691-98d9fd5ab4ff.png)

This does not seem to be consistent with your above statement.
