### ISSUE TITLE
fail to build wheel when updating via pip

### ISSUE THREAD

**Issue by mbertucci47** [fplll/fpylll#242]
I'm trying to update fpylll from version 0.5.7 to 0.5.9 in WSL with Ubuntu 22.10. Running `pip install -v -U fpylll --log log.txt` fails to build the wheel and produces this [log.txt](https://github.com/fplll/fpylll/files/10513221/log.txt). [This issue](https://github.com/fplll/fpylll/issues/223) seemed relevant, but my installed fplll-tools is 5.4.2-1 (current is 5.4.4). Is this not recent enough?

I think this is the main error (but I'm not sure at all):
```
error: Command "x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Isrc/fpylll/fplll -I/home/saints4774/.local/lib/python3.10/site-packages/cysignals -I/usr/include -I/home/saints4774/.local/lib/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -c build/src/fpylll/fplll/gso.cpp -o build/temp.linux-x86_64-cpython-310/build/src/fpylll/fplll/gso.o -std=c++11" failed with exit status 1
```
For what it's worth, I'm also having trouble updating `sagemath-standard` and `sage-conf` past versions 9.5. Not sure if it's related, but these are the only three pip packages I'm having issues with.

Thanks in advance for any help.

**Comment by StHagel** [comment]
I was having the same issue on Linux Mint 21.1. It was caused by the version of `libfplll` provided by apt being outdated.
Manually installing it from source (https://github.com/fplll/fplll) solved this issue for me.
