### ISSUE TITLE
Incompatibility with Python 3.12

### ISSUE THREAD

**Issue by encukou** [fplll/fpylll#246]
Python 3.12 changes the *int*ernal representation of `int` objects (to speed up common cases). Usage of `Py_SIZE` and `ob_digit` in `gmp/pylong.pyx` will fail.

The supported way of extracting the value of integers (if they don't fit in a C `long long`) is the Python method [to_bytes](https://docs.python.org/3/library/stdtypes.html#int.to_bytes), and there's `from_bytes` to go back. (If this is too slow for fpylll, please chime in in [the discussion](https://discuss.python.org/t/20045).)

(edit) See also: https://github.com/python/cpython/pull/101292

**Comment by malb** [comment]
Thank you for flagging this! I don't think we need every last drop of performance here. I anyone would prepare a PR, that'd be fab :)

**Comment by malb** [comment]
See https://github.com/sagemath/sage/pull/36181
