### ISSUE TITLE
Can't run setup.py build_ext

### ISSUE THREAD

**Issue by jameshoweee** [fplll/fpylll#25]
The initial error said that fplll/nr.h was not found as nr.h has moved into sub-directory nr. I corrected this errors and any subsequent errors to do with the new directory structure regarding fplll. Upon doing this I preceded further how these errors I cannot debug, due to fpylll being out of date with fplll. Below are the error messages being received, tested on both python 2 and 3, would someone else be able to test the fpylll against the latest version of fplll? Happy to give any more information if required.

`building 'util' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jhowe/test/lib/python2.7/site-packages/cysignals -I/home/jhowe/test/include -I/home/jhowe/anaconda2/include/python2.7 -c build/src/fpylll/util.cpp -o build/temp.linux-x86_64-2.7/build/src/fpylll/util.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/include/c++/5/array:35:0,
                 from /home/jhowe/test/include/fplll/enum/enumerate.h:20,
                 from build/src/fpylll/util.cpp:328:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from build/src/fpylll/util.cpp:332:0:
/home/jhowe/test/include/fplll/fplll.h:22:2: error: #error fplll needs at least a C++11 compliant compiler
 #error fplll needs at least a C++11 compliant compiler
  ^
In file included from /home/jhowe/test/include/fplll/nr/nr.h:17:0,
                 from build/src/fpylll/util.cpp:321:
/home/jhowe/test/include/fplll/nr/nr_FP.inl: In constructor ‘fplll::FP_NR<F>::FP_NR(double)’:
/home/jhowe/test/include/fplll/nr/nr_FP.inl:33:46: warning: delegating constructors only available with -std=c++11 or -std=gnu++11
   inline FP_NR<F>(const double d) : FP_NR<F>() {*this = d;};
                                              ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl: At global scope:
/home/jhowe/test/include/fplll/nr/nr_FP.inl:339:35: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F>&& operator+(FP_NR<F> &&a, const FP_NR<F> &b)
                                   ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:386:35: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F>&& operator*(FP_NR<F> &&a, const FP_NR<F> &b) {
                                   ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:414:35: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F>&& operator*(FP_NR<F> &&a, double b) {
                                   ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:431:35: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F>&& sqrt(FP_NR<F> &&a) {
                                   ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:442:35: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F>&& abs(FP_NR<F> &&a) {
                                   ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:454:35: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F>&& floor(FP_NR<F> &&a) {
                                   ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:466:35: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F>&& log(FP_NR<F> &&a) {
                                   ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:477:35: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F>&& exp(FP_NR<F> &&a) {
                                   ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:488:36: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F> &&pow_si(FP_NR<F> &&a, long b) {
                                    ^
/home/jhowe/test/include/fplll/nr/nr_FP.inl:499:36: error: expected unqualified-id before ‘&&’ token
 template <class F> inline FP_NR<F> &&root(FP_NR<F> &&a, unsigned int b) {
                                    ^
In file included from build/src/fpylll/util.cpp:328:0:
/home/jhowe/test/include/fplll/enum/enumerate.h:53:5: error: ‘array’ does not name a type
     array<enumf, DMAX> rdiag, dist, center, centerPartSum, maxDists, alpha;
     ^
/home/jhowe/test/include/fplll/enum/enumerate.h:54:5: error: ‘array’ does not name a type
     array<enumxt, DMAX> x, dx, ddx, centerLoopBg;
     ^
/home/jhowe/test/include/fplll/enum/enumerate.h: In member function ‘bool fplll::Enumeration<FT, MaxDimension>::nextPosUp()’:
/home/jhowe/test/include/fplll/enum/enumerate.h:65:13: error: ‘x’ was not declared in this scope
             x[k] += dx[k];
             ^
/home/jhowe/test/include/fplll/enum/enumerate.h:65:21: error: ‘dx’ was not declared in this scope
             x[k] += dx[k];
                     ^
/home/jhowe/test/include/fplll/enum/enumerate.h:66:13: error: ‘ddx’ was not declared in this scope
             ddx[k] = -ddx[k];
             ^
/home/jhowe/test/include/fplll/enum/enumerate.h:73:15: error: ‘x’ was not declared in this scope
             ++x[k];
               ^
build/src/fpylll/util.cpp: At global scope:
build/src/fpylll/util.cpp:803:15: warning: ‘__pyx_f_9cysignals_7signals_print_backtrace’ defined but not used [-Wunused-variable]
 static void (*__pyx_f_9cysignals_7signals_print_backtrace)(void); /*proto*/
               ^
build/src/fpylll/util.cpp:804:15: warning: ‘__pyx_f_9cysignals_7signals__sig_on_interrupt_received’ defined but not used [-Wunused-variable]
 static void (*__pyx_f_9cysignals_7signals__sig_on_interrupt_received)(void); /*proto*
               ^
build/src/fpylll/util.cpp:805:15: warning: ‘__pyx_f_9cysignals_7signals__sig_on_recover’ defined but not used [-Wunused-variable]
 static void (*__pyx_f_9cysignals_7signals__sig_on_recover)(void); /*proto*/
               ^
build/src/fpylll/util.cpp:806:15: warning: ‘__pyx_f_9cysignals_7signals__sig_off_warning’ defined but not used [-Wunused-variable]
 static void (*__pyx_f_9cysignals_7signals__sig_off_warning)(char const *, int); /*pro
               ^
error: command 'gcc' failed with exit status 1
`

**Comment by malb** [comment]
fplll is being reorganised heavily right now in a coding sprint and fpylll has trouble keeping up. If you check out fd0369cb7c604d77c3ed1644bf3408ce29e0126d of fplll and build against that, it will work.

**Comment by jameshoweee** [comment]
Thanks Martin, will try again tomorrow!

**Comment by malb** [comment]
This should be fixed now. closing.
