### ISSUE TITLE
IntegerMatrix.from_matrix does not support numpy arrays

### ISSUE THREAD

**Issue by verdiverdiverdi** [fplll/fpylll#251]
```
import numpy as np
from fpylll import IntegerMatrix
B = np.eye(5)
Bfpy = IntegerMatrix.from_matrix(B)
```

gives

`NotImplementedError: Type '<class 'numpy.float64'>' not supported`

that ultimately comes from set_matrix calling _set ([here](https://github.com/fplll/fpylll/blob/master/src/fpylll/fplll/integer_matrix.pyx)) which calls assign_mpz ([here](https://github.com/fplll/fpylll/blob/65954104ad59fcf2f5240beaa714be9bcdee67d8/src/fpylll/io.pyx#L36C10-L36C20)).

This is not the end of the world, as one can do double list comprehension and cast to a python int -- but it would be nice if from_matrix supported numpy arrays natively.

**Comment by malb** [comment]
It's not quite clear to me what should happen here. Would we just round?

**Comment by verdiverdiverdi** [comment]
Apologies, I meant e.g.

```
import numpy as np
from fpylll import IntegerMatrix
B = np.eye(5, dtype=np.int32)
Bfpy = IntegerMatrix.from_matrix(B)
```

which gives

`NotImplementedError: Type '<class 'numpy.int32'>' not supported`

which seems true for all integer types numpy understands.

**Comment by verdiverdiverdi** [comment]
I guess the solution is just to do this casting to a python integer "behind the scenes" in these cases?

**Comment by malb** [comment]
Yup, I agree with that. Shouldn't be too hard to add.
