### ISSUE TITLE
Please make a new release (on PyPI too)

### ISSUE THREAD

**Issue by dimpase** [fplll/fpylll#261]
Please make a new release (on PyPI too), as I just saw `pip install fpyll` (i.e. pulling version 0.6.0 from PyPI) and up to date python 3.10 venv with latest Cython, setuptools, etc, erroring out with
```
ModuleNotFoundError: No module named 'Cython'
```

Installing from master branch, i.e. `pip install git+ssh://git@github.com/fplll/fpylll.git`, worked.

_Originally posted by @dimpase in https://github.com/fplll/fpylll/issues/258#issuecomment-1902137158_

**Comment by malb** [comment]
done
