### ISSUE TITLE
allow manual precision in pruner also when GSO objects are passed

### ISSUE THREAD

**Issue by malb** [fplll/fpylll#32]
We currently just pick the GSO precision, but that -- in principle -- is a separate thing. Reported by @lducas

**Comment by lducas** [comment]
If this could include a hook for dd/qd that'd be great (mpfr is probably an overkill here)

**Comment by malb** [comment]
Can do, but did you run into performance problems? In my limited experience the pruner was always fast enough and/or double precision was enough.

**Comment by lducas** [comment]
Let's say its not urgent, but according to a discussion Phong, high
precision becomes very necessary for solving BDD and such (more precisely,
when one targets quite low success proba).

Also, if one targets a BDD in dimension 500, then performances will start
becoming a serious issue (the algorithm is at least cubic, even for a fixed
precision).

-- L

2016-08-29 11:37 GMT+02:00 Martin Albrecht <notifications@github.com>:

**Comment by malb** [comment]
Closing as irrelevant now due to API changes.
