### ISSUE TITLE
Precision on BKZ

### ISSUE THREAD

**Issue by yuyang-Tsinghua** [fplll/fpylll#38]
Hi Martin,

I want to run BKZ on a 220-dim LLL basis which is reduced by LLL.Wrapper, but it shows an error "fpylll.util.ReductionError: infinite loop in babai". The following is the main code and attached is the source file.
[demo.tar.gz](https://github.com/fplll/fpylll/files/478074/demo.tar.gz)

Could you please tell me how to make BKZ work for high dimension? Thank you.

```
from math import log
from fpylll import IntegerMatrix, GSO, LLL
from fpylll.algorithms.bkz import BKZReduction as BKZ1
from fpylll import BKZ as BKZ
``` 

```
B = IntegerMatrix.from_file("lll")
param = BKZ.Param(block_size=2)
BKZ1(B)(params=param)

```

**Comment by malb** [comment]
You can now pass GSO and LLL objects to `BKZ1` which allows you to pick your favourite precision. Hope this helps.

**Comment by yuyang-Tsinghua** [comment]
Yes, it works now. Thank you very much.
