### ISSUE TITLE
fpylll does not compile on Cygwin due to lack of long double

### ISSUE THREAD

**Issue by embray** [fplll/fpylll#40]
There are several places in fpylll where `long double` versions of some templates are used explicitly, but that are not defined when fplll is built on Cygwin due to the macro `FPLLL_WITH_LONG_DOUBLE` not being defined.

There are quite a number of places in fpylll where exceptions would have to be made for this case, and it's a bit of a pain.  Maybe simpler would be to define the `long double` interfaces on Cygwin but warn when using `long double ` types explicitly.

Related: fplll/fplll#212

**Comment by embray** [comment]
I've actually gone through mechanically and bracketed most of the long double code in fpylll which seems to be doing the trick.  I'll have a PR shortly.

**Comment by malb** [comment]
thanks!
