### ISSUE TITLE
s/f/util.pyx generates a non-buildable C++ source  

### ISSUE THREAD

**Issue by jgmbenoit** [fplll/fpylll#42]
I am trying to build fpylll on an uptodate Sid Debian box: I get the error message:

In file included from build/src/fpylll/util.cpp:331:0:
build/src/fpylll/util.cpp: In function ‘int __pyx_f_6fpylll_4util_check_descent_method(PyObject*)’:
build/src/fpylll/util.cpp:1571:22: error: expected unqualified-id before numeric constant
     __pyx_r = fplll::PRUNER_METHOD_GRADIENT;
                      ^
build/src/fpylll/util.cpp:1600:22: error: expected unqualified-id before numeric constant
     __pyx_r = fplll::PRUNER_METHOD_NM;
                      ^
build/src/fpylll/util.cpp:1629:22: error: expected unqualified-id before numeric constant
     __pyx_r = fplll::PRUNER_METHOD_HYBRID;
                      ^
It appears that the PRUNER_METHOD_* are defined as macros in fplll/pruner.h .

**Comment by kiwifb** [comment]
Which version of gcc are you using. Works here, on Gentoo, with 5.4.0. I would also be curious to know why the generated code is off by one line for me compared to you.

**Comment by jgmbenoit** [comment]
gcc (Debian 6.2.0-6) 6.2.0 20161010
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by kiwifb** [comment]
I am not setup to try that but I wouldn't be half surprised.

**Comment by malb** [comment]
it works for me: Debian/testing with: `gcc (Debian 6.2.0-6) 6.2.0 20161010`

**Comment by jgmbenoit** [comment]
Ok. Can you send your generated s/f/util.cpp ?

**Comment by malb** [comment]
Here it is: https://transfer.sh/HJrXn/util.cpp

**Comment by jgmbenoit** [comment]
Thanks. grep PRUNER_METHOD_ util.cpp (yours) gives:
 *         return PRUNER_METHOD_GRADIENT
 *         return PRUNER_METHOD_GRADIENT
 *         return PRUNER_METHOD_GRADIENT             # <<<<<<<<<<<<<<
 *         return PRUNER_METHOD_NM
    __pyx_r = fplll::PRUNER_METHOD_GRADIENT;
 *         return PRUNER_METHOD_GRADIENT
 *         return PRUNER_METHOD_GRADIENT
 *         return PRUNER_METHOD_NM
 *         return PRUNER_METHOD_GRADIENT
 *         return PRUNER_METHOD_NM             # <<<<<<<<<<<<<<
 *         return PRUNER_METHOD_HYBRID
    __pyx_r = fplll::PRUNER_METHOD_NM;
 *         return PRUNER_METHOD_GRADIENT
 *         return PRUNER_METHOD_NM
 *         return PRUNER_METHOD_NM
 *         return PRUNER_METHOD_HYBRID
 *         return PRUNER_METHOD_NM
 *         return PRUNER_METHOD_HYBRID             # <<<<<<<<<<<<<<
    __pyx_r = fplll::PRUNER_METHOD_HYBRID;
 *         return PRUNER_METHOD_NM
 *         return PRUNER_METHOD_HYBRID
 *         return PRUNER_METHOD_HYBRID
 *         return PRUNER_METHOD_GRADIENT

**Comment by jgmbenoit** [comment]
as in my box. :-)

**Comment by jgmbenoit** [comment]
I guess that you are compiling with the material in the git repositories. I have just noticed that the macros PRUNER_METHOD_ are no more macros but enum  _s defined in fplll/fplll/defs.h . This explains that. In short I cannot fpylll against the released fplll . Do you plane to release a new source ball of fplll soon ?

**Comment by malb** [comment]
Ah, we should definitely do that.

**Comment by malb** [comment]
Hang on, have you tried with https://github.com/fplll/fplll/releases/tag/5.0.3rc0 ?

**Comment by jgmbenoit** [comment]
I am packaging fpylll on behalf of the Debian Science Team (and the Deian Sage Team), so basiclly I am working with Debian balls. It appears that the currently packaged version of fplll is 5.0.2, but not 5.0.3rc0, hence the trouble. On the other hand, it might be that the package maintainer of fplll is reluctant to package 5.0.3rc0 because it is a RC.

**Comment by malb** [comment]
I just pushed https://github.com/fplll/fplll/releases/tag/5.0.3 which should fix your troubles (?)

**Comment by jgmbenoit** [comment]
Indeed it should fix the trouble. I will let you know. Thanks.

**Comment by jgmbenoit** [comment]
It is fixed, so I am closing the issue. Thanks you very much for your prompt action.
