### ISSUE TITLE
lintian spelling complain: allow one

### ISSUE THREAD

**Issue by jgmbenoit** [fplll/fpylll#43]
[Lintian](https://lintian.debian.org/) complains about the usage of `allow to' in the funcfion test_abort encoded in fpylll/fplll/bkz.pyx :

:param int max_no_dec: number of rounds we allow to be stuck

Lintian suggests to replace "allow to" by "allow one to": Lintian is not that smart.

Being not a native English speaker, I cannot figure out a proper replacement:
can any one suggest a decent replacement to silence lintian ?

**Comment by malb** [comment]
Me neither, but this looks correct to me.

**Comment by jgmbenoit** [comment]
Parallelly I initialized a thread in the [debian-mentors list](https://lists.debian.org/debian-mentors/2016/10/msg00318.html)

**Comment by infinity0** [comment]
FYI for future reference "<noun> we allow to be <passive verb>" is correct English, it's just a false positive in Lintian that is hard to avoid. The new version is also fine however, no need to revert.
