### ISSUE TITLE
Running setup.py --help or clean will build cython files

### ISSUE THREAD

**Issue by infinity0** [fplll/fpylll#46]
This is not a major issue, but it does waste a bit of time. Hopefully if I bring this up here early, a solution will be figured out before this anti-pattern propagates to other cython projects too.

**Comment by malb** [comment]
Isn't what we're doing what the Cython documentation recommends? https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#multiple-cython-files-in-a-package

**Comment by infinity0** [comment]
Oh right, it does look that way yes. I'm not familiar with Cython. However, it's still not a good pattern to be recommending; I'll file this upstream to cython instead.
