### ISSUE TITLE
Convertion between basis systems

### ISSUE THREAD

**Issue by lducas** [fplll/fpylll#47]
depending on the algorithm desired, vectors are needed in different coordinates systems:
- canonical system of R^m
- basis B (same than the lattice)
- Gram-Schmidt basis B*

Having the 6 conversions routine available in fpylll would be extremely convenient.

**Comment by malb** [comment]
Are you going to send a PR on this (since you mentioned you have this implemented)?

**Comment by lducas** [comment]
Oh, there was some misunderstanding... I did implemented it in my playground, but it has nothing to do with fplll.... I can send you the code but I'm unsure it is of any use. If with this clarification you want to reassign the task to me, that'd be fair ;)

**Comment by lducas** [comment]
Thanks Martin. I guess that is enough for now (ideally we'd do that in C for speed, but let's assume those are not function we would call often enough for a serious difference). For naming, what about gs_to_canon and canon_to_gs ?

**Comment by malb** [comment]
I personally like `slurp`/`barf`, they are somewhat canonical in the lisp world it seems, but I'm not insisting on them. If they are methods on `MatGSO` I'm not to keen on `xxx_to_yyy` but would rather have something that indicates casting `in` and `out`.

You're right `n*[0]` would have perhaps been clearer.

**Comment by malb** [comment]
PS: I agree we should push this down to C++/fplll. Let's fix the interface here first, e.g. how to call it, and then I can push it down.
