### ISSUE TITLE
error in sd_tour

### ISSUE THREAD

**Issue by lducas** [fplll/fpylll#48]
@malb , @blowfish880 

Hi guys, 

I've been trying to use SD-BKZ, but got this error message.

```bash
File "src/fpylll/fplll/bkz.pyx", line 534, in fpylll.fplll.bkz.BKZReduction.sd_tour (build/src/fpylll/fplll/bkz.cpp:7291)
AttributeError: 'fpylll.fplll.gso.MatGSO' object has no attribute 'dim'
```

I'm also a bit confused by the current interface. we do have access to an sd_tour procedure, and the comments mention bkz.__run__ to offer BKZ, SD-BKZ, and SLIDE, but I couldn't find a flag or a parameter to switch away from good old BKZ.

Example:
```python
from fpylll import GSO, IntegerMatrix, BKZ, LLL

def make_integer_matrix(m, n):
    A = IntegerMatrix(m, n)
    A.randomize("uniform", bits=m+n)
    return A

A = make_integer_matrix(30, 30)
M = GSO.Mat(A, float_type='ld')
lll_obj = LLL.Reduction(M)
param = BKZ.Param(block_size=3, strategies="default.json")
bkz = BKZ.Reduction(M, lll_obj, param)
bkz.sd_tour(2, param, 0, 30)
```

**Comment by lducas** [comment]
PS: replacing all instances of `M.dim`  to `M.B.nrows` in bkz.pyx now leads to a segfault:
```bash
  File "sd_tour_bug.py", line 15, in <module>
    bkz.sd_tour(2, param, 0, 30)
  File "src/fpylll/fplll/bkz.pyx", line 547, in fpylll.fplll.bkz.BKZReduction.sd_tour (build/src/fpylll/fplll/bkz.cpp:6196)
  File "src/cysignals/signals.pyx", line 109, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1686)
cysignals.signals.SignalError: Segmentation fault
```

**Comment by malb** [comment]
Hi Leo, you must call `bkz.lll_obj()` before calling `bkz.slide_tour()`. How shall we address this?

1. Unconditionally calling `bkz.lll_obj()` in `bkz.slide_tour()` or
2. adding a warning?

I'm somewhat inclined to go for 1.

**Comment by lducas** [comment]
Feel free to close, I can run it now. 

As for your question:

I wouldn't do 1 in the tour function, only in the bkz function (which is probably already done except if NOLLL flag is up). I only used the tour function since I did not have the option, my understanding is that those internal function are given to people want very low level control, and they shouldn't be forced to re run LLL at each tour.
