### ISSUE TITLE
What's up with includes before the module docstring??

### ISSUE THREAD

**Issue by jdemeyer** [fplll/fpylll#65]
This is more a question than an issue, but I wonder why the sources look like
```cython
# -*- coding: utf-8 -*-
include "fpylll/config.pxi"
include "cysignals/signals.pxi"
^L
"""
Parameters for Block Korkine Zolotarev algorithm.

..  moduleauthor:: Martin R.  Albrecht <martinralbrecht+fpylll@googlemail.com>
"""
```
with the `^L` representing a form-feed character. In particular, why put the `include` **before** the module docstring?

I am asking because I'm planning a pull request, but I don't get this code style.

**Comment by malb** [comment]
You're right, there is no good reason for this ordering. Feel free to ignore. The ^L is a structuring element to split files into logical parts (it's supported by emacs, no idea if other editors support it, too).

**Comment by jdemeyer** [comment]
I'm just worried that the module docstring might not be recognized as a module docstring if it's not the first thing in the file.

**Comment by malb** [comment]
Yeah, better to follow convention here. I can fix it up or feel free to do it if you're on those file anyway.

**Comment by jdemeyer** [comment]
> I can fix it up

Please do.
