### ISSUE TITLE
call to CVP getting stuck

### ISSUE THREAD

**Issue by jiji-angel** [fplll/fpylll#74]
Call to CVP.closest_vector(A, t), getting stuck.
No error message comes but the call keeps executing i guess.
Attaching the A matrix and t vector.
[A.txt](https://github.com/fplll/fpylll/files/1130342/A.txt)

[t.txt](https://github.com/fplll/fpylll/files/1130347/t.txt)

I'm new to this library, can't figure out what going wrong.

**Comment by malb** [comment]
Can you give more details, so we don't have to manually inspect/run your instance? What dimensions are you looking at, how reduced is your basis? How long is "too long"?

**Comment by jiji-angel** [comment]
My lattice dimension is 101.
I reduced the basis using BKZReduction.

**Comment by malb** [comment]
What block size? Looks like you're simply trying to run a very long computation.

**Comment by jiji-angel** [comment]
Tried block sizes 20 and 30.
Both giving the same issue.
Code snippet:
`beta = 30
param =  BKZ.Param(block_size=beta)

reducedA = IntegerMatrix.from_matrix(A)
bkz = BKZReduction(reducedA)
_ = bkz(param)
z = CVP.closest_vector(reducedB, t)`

**Comment by malb** [comment]
This computation is expected to take a long time, you'll need to preprocess your basis using stronger lattice reduction. Also, you'll want to use the provided reduction strategies `BKZ.DEFAULT_STRATEGY` to speed up the BKZ preprocessing. Then you'll need to compute pruning parameters using the `pruner` for your CVP and run closest vector with those new pruning parameters.
