### ISSUE TITLE
Help needed in BKZ2.0 usage (from fpylll's BKZReduction)

### ISSUE THREAD

**Issue by jiji-angel** [fplll/fpylll#76]
I'm trying to use BKZ2.0, from fpylll's BKZReduction. Accoring to [this post](https://martinralbrecht.wordpress.com/2016/08/22/fplll-5-0/), this BKZ2.0 implementation comes with extreme pruning. I'm trying to implement the cryptanalysis as in ["Lattice Enumeration Using Extreme Pruning"](https://link.springer.com/content/pdf/10.1007%2F978-3-642-13190-5_13.pdf). But I'm never getting the results are mentioned by them. Can someone help me with an example where BKZ2.0 with extreme pruning is used.

**Comment by malb** [comment]
Extreme pruning is used by default for large block sizes:

```python
from fpylll import *
strategies = load_strategies_json(BKZ.DEFAULT_STRATEGY)
for strategy in strategies[50:]:
    print strategy
```

This will print lines such as `Strategy< 90, (70), 0.05-0.19>` where `90` is the block size, `70` is the preprocessing block size used, and `0.05-0.19` is the probability of success target by enumeration for various enumeration radii.

**Comment by jiji-angel** [comment]
Hi Martin,

Thanks for the help. Some more queries:
- What is meant by 'large' block size? From what block size onwards (approx.) is it large?
- Should I be selecting some strategy manually in my code, even after opting for `BKZ.DEFAULT_STRATEGY`?
