### ISSUE TITLE
enumerate function

### ISSUE THREAD

**Issue by drazioti** [fplll/fpylll#86]
I thought that the following code

```
from fpylll.fplll.gso import MatGSO
from fpylll.fplll.integer_matrix import IntegerMatrix
from fpylll.fplll.enumeration import Enumeration,EvaluatorStrategy
def gauss(radius):
    A = IntegerMatrix.from_matrix([[1,0], [0,1]] ) #define ZZ^2
    M = MatGSO(A)
    _ = M.update_gso()
    enum = Enumeration(M,nr_solutions = 20)
    e1 = enum.enumerate(0, 2, radius, 0)
    e2 = [item[0] for item in e1]
    print e2
```

would returns **all** the integer points inside the set {(x,y):x^2+y^2<=radius}.
Instead I got
```
>>>gauss(1)
[(0.0, 1.0), (1.0, 0.0)]
>>>gauss(2)
[(0.0, 1.0), (1.0, 0.0), (-1.0, 1.0), (1.0, 1.0)]
```
Also, I tried the following 
`enum = Enumeration(M,nr_solutions = 20, strategy=EvaluatorStrategy.FIRST_N_SOLUTIONS)
`
and got the same result.
How to get all the points (i.e. with all possible signs)?

**Comment by malb** [comment]
We're just calling fplll and return whatever it returns here, but I'd guess that those vectors are simply suppressed because they are not geometrically interesting (?)

**Comment by drazioti** [comment]
I can't see why (1,0) is more _interesting_ than (-1,0). I believe fplll, must returns all the possible solutions.

**Comment by malb** [comment]
But if you already have (1,0) then (-1, 0) is not interesting, no?

**Comment by drazioti** [comment]
ok. In the case of gauss(2) fplll returns the points (1,0),(0,1),(1,1),(-1,1). 
So, (if I follow your argument)  (-1,1) is not interesting, since (1,1) already computed from fplll. Although, (-1,1) was computed from fplll. Ii doesn't seem that fplll misses some points according to some specific restrictions. For instance if fplll returns only the points with positive sign, that, it does make sense.

**Comment by malb** [comment]
Mhh, but `(-1, 1)` is not `-1 * (1, 1) = (-1,-1)` so I don't get your point. What am I missing?

**Comment by drazioti** [comment]
It seems that I missed something...Maybe a minor addition to the documentation of enumeration, will clear this behavior. So, in order to get **all** the solutions, in the list say [a,b,c,...] returned by the enumeration, someone has to add the vectors [-a,-b,-c,...].
