### ISSUE TITLE
Help regarding enumerate function

### ISSUE THREAD

**Issue by rahulrchandran** [fplll/fpylll#87]
What are the parameters passed in to enumerate function defined inside Enumeration class.

In my experiment, I have numbers in the range 2^160 inside the Integer Lattice. In comparison to "test_cvp.py" given in "tests" folder, The above integer Lattice is giving me correct vector when I call the CVP.closest_vector() function. Now suppose I want to test it using Enumeration what are the parameters that are to be passed in enumerate function ? 

In the below given definition (taken from "enumeration.pyx"), I am assuming "first" is the index of first row and "last" is the index of last row of the basis matrix. I am not able to understand what is to be passed to variables "max_dist" and "max_dist_expo". In your example in "test_cvp.py" you had passed max_dist=2 and max_dist_expo = 40. How did you arrive at those numbers?

Also what are the possible values for param "pruning" . 

Currently I am getting error as "EnumerationError: No vector found." when I call enumerate function.

```

enumerate(self, int first, int last, max_dist, max_dist_expo, target=None, subtree=None, pruning=None, dual=False, subtree_reset=False)
        :param int first:      first row
        :param int last:       last row (exclusive)
        :param max_dist:       length bound
        :param max_dist_expo:  exponent of length bound
        :param target:         target coordinates for CVP/BDD or ``None`` for SVP
        :param subtree:
        :param pruning:        pruning parameters
        :param dual:           run enumeration in the primal or dual lattice.
        :param subtree_reset:
        :returns: list of pairs containing the solutions' coefficient vectors and their lengths

```
Thanks,

**Comment by malb** [comment]
Hi, `max_dist` and `max_dist_expo` specify the enumeration radius as `max_dist * 2^max_dist_expo`, a safe choice for SVP is the norm of the first vector in the basis.

**Comment by lducas** [comment]
Just in case: note that all norms are given by they square in the software. e.g., if you are looking for the vector [1, 2], set max_dist=5, not max_dist=sqrt(5).

**Comment by rahulrchandran** [comment]
okay. Thank you so much.
