### ISSUE TITLE
Uniformize default value for parameter tracer in bkz.py

### ISSUE THREAD

**Issue by lducas** [fplll/fpylll#92]
Sometime no default value is given, sometimes None, sometime dummy_tracer. I guess it could be uniformized.

**Comment by malb** [comment]
I see only one offender at https://github.com/fplll/fpylll/blob/master/src/fpylll/algorithms/bkz.py#L146 (?)

**Comment by lducas** [comment]
Hum, I thought I see more, maybe in other files. But bkz2.py seems ok...
